### ISSUE TITLE
JS ERROR SyntaxError: Unexpected identifier 'module' 

### ISSUE THREAD

**Issue by grvermeulen** [m-abs/nativescript-accessibility-ext-private#12]
Hi, 
I just included the plugin. During my build for iOS I got this error: 

file:///app/tns_modules/@nota/nativescript-accessibility-ext/ui/core/view:1:8: JS ERROR SyntaxError: Unexpected identifier 'module'

We're working with tns core module 3.0.1 Could you help us out? Thnx.

Guido

**Comment by m-abs** [comment]
Hi,

Thank you for the bug rapport. It should be fixed in v3.0.0-alpha.5
The package contained a file that shouldn't have been there, `ui/core/view`. It was an old `d.ts`-file...

**Side note:** The project have been moved to my employers organisation and this repo have been left for historical purposes.

New project URL:
https://github.com/Notalib/nativescript-accessibility-ext

**Comment by grvermeulen** [comment]
Thanks so much for the fast reply and the fix ! this will help my project a lot!
