### ISSUE TITLE
Peer dependencies tns core

### ISSUE THREAD

**Issue by grvermeulen** [m-abs/nativescript-accessibility-ext-private#3]
Hi,
installation of the plugin fails because we are using tns-core-modules 3.0.1 
We cannot downgrade our core modules. Is it possible to fix this dependency to a compatable version? 
package.json states: 

"peerDependencies": {
    "tns-core-modules": "^2.5.0"
  }

**Comment by m-abs** [comment]
Hi,

Thank you very much for your bug report.

Unfortunately we haven't updated the plugin to nativescript-3.x yet.
The current version won't work with "tns-core-modules@^3.0.0" due to breaking changes in v3.x. 

We're working on updating the plugin in the branch tns-3.0, but its still a WIP.
See: https://github.com/m-abs/nativescript-accessibility-ext/tree/tns-3.0

**Comment by m-abs** [comment]
Hi again,

We've published v3.0.0-alpha.2 of the plug-in you can try.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by grvermeulen** [comment]
Thanks for the reply! Got a new issue now, but this one is fixed!
